variable = input('input something: ')
print(f'The primitive type is: {type(variable)}')
print(f"It's just blank spaces: {variable.isspace()}")
print(f"It's a number: {variable.isnumeric()}")
print(f"It's alphabetic: {variable.isalpha()}")
print(f"It's alphanumeric {variable.isalnum()}")
print(f'Is in uppercase: {variable.isupper()}')
print(f'Is in lowercase: {variable.islower()}')
print(f'Is capitalized: {variable.istitle()}')